-- Migration SQLite to PostgreSQL
-- Generated from: ctba_platform.db
-- Drop existing tables first (if needed)

-- DROP TABLE IF EXISTS affected_products CASCADE;
-- DROP TABLE IF EXISTS imports_audit CASCADE;
-- DROP TABLE IF EXISTS cves CASCADE;
-- DROP TABLE IF EXISTS technologies CASCADE;
-- DROP TABLE IF EXISTS users CASCADE;

-- CREATE TABLES
-- ====================================================================

-- Table: affected_products
CREATE TABLE affected_products (
    id SERIAL PRIMARY KEY,
    cve_id VARCHAR(20) NOT NULL,
    vendor VARCHAR(100) NOT NULL,
    product VARCHAR(100) NOT NULL,
    confidence DECIMAL(3,2) DEFAULT 0.0,
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY (cve_id) REFERENCES cves(cve_id) ON DELETE CASCADE
);

-- Table: bulletin_attachments
CREATE TABLE bulletin_attachments (
            id SERIAL PRIMARY KEY ,
            bulletin_id INTEGER NOT NULL,
            filename TEXT NOT NULL,
            path TEXT NOT NULL,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (bulletin_id) REFERENCES bulletins(id) ON DELETE CASCADE
        );

-- Table: bulletin_logs
CREATE TABLE bulletin_logs (
            id SERIAL PRIMARY KEY ,
            bulletin_id INTEGER NOT NULL,
            action TEXT,
            region TEXT,
            recipients TEXT,
            message TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (bulletin_id) REFERENCES bulletins(id) ON DELETE CASCADE
        );

-- Table: bulletins
CREATE TABLE bulletins (
            id SERIAL PRIMARY KEY ,
            title TEXT NOT NULL,
            body TEXT,
            regions TEXT,
            status TEXT DEFAULT 'DRAFT' CHECK(status IN ('DRAFT','SENT','NOT_PROCESSED')),
            created_by TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            sent_at TIMESTAMP,
            last_reminder INTEGER DEFAULT 0
        );

-- Table: cve_actions
CREATE TABLE cve_actions (
            id SERIAL PRIMARY KEY ,
            cve_id TEXT NOT NULL,
            action TEXT CHECK(action IN ('ACCEPTED', 'REJECTED', 'DEFERRED')),
            analyst TEXT NOT NULL,
            comments TEXT,
            action_date TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
            FOREIGN KEY (cve_id) REFERENCES cves(cve_id) ON DELETE CASCADE
        );

-- Table: cves
CREATE TABLE cves (
    id SERIAL PRIMARY KEY,
    cve_id VARCHAR(20) UNIQUE NOT NULL,
    description TEXT,
    severity VARCHAR(20),
    cvss_score DECIMAL(4,1),
    cvss_version VARCHAR(10),
    published_date TIMESTAMP,
    status VARCHAR(20) DEFAULT 'PENDING',
    imported_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    last_updated TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    reviewed_at TIMESTAMP,
    analyst VARCHAR(100),
    source VARCHAR(100),
    CHECK(severity IN ('CRITICAL', 'HIGH', 'MEDIUM', 'LOW'))
);

-- Table: regions
CREATE TABLE regions (
            id SERIAL PRIMARY KEY ,
            name TEXT UNIQUE NOT NULL,
            description TEXT,
            recipients TEXT,
            created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
        );

-- Table: technologies
CREATE TABLE technologies (
    id SERIAL PRIMARY KEY,
    vendor VARCHAR(100) NOT NULL,
    product VARCHAR(100) NOT NULL,
    version VARCHAR(50),
    status VARCHAR(50) DEFAULT 'PENDING',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UNIQUE(vendor, product)
);

-- Table: users
CREATE TABLE users (
    id SERIAL PRIMARY KEY,
    username VARCHAR(50) UNIQUE NOT NULL,
    email VARCHAR(100) UNIQUE NOT NULL,
    password_hash VARCHAR(255) NOT NULL,
    role VARCHAR(20) DEFAULT 'analyst',
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);


-- INSERT DATA
-- ====================================================================

INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (1, 'CVE-2026-1106', 'Php', 'Core', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (2, 'CVE-2026-1107', 'Php', 'Core', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (3, 'CVE-2026-1108', 'Fizz Is On The Way', 'Vuls_Protocol', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (7, 'CVE-2026-1109', 'Fizz Is On The Way', 'Vuls_Protocol', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (12, 'CVE-2025-15533', 'Raysan5', 'Raylib', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (16, 'CVE-2026-1110', 'Fizz Is On The Way', 'Vuls_Protocol', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (20, 'CVE-2026-1111', 'Java', 'Runtime', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (22, 'CVE-2025-15534', 'Raysan5', 'Raylib', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (26, 'CVE-2026-1112', 'Java', 'Runtime', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (27, 'CVE-2025-15535', 'Nicbarker', 'Clay', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (32, 'CVE-2025-15536', 'Byvoid', 'Opencc', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (42, 'CVE-2026-1118', 'Php', 'Core', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (43, 'CVE-2026-1119', 'Php', 'Core', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (60, 'CVE-2026-0863', 'Docker', 'Container', 0.8);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (61, 'CVE-2026-0863', 'Python', 'Core', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (70, 'CVE-2026-1126', 'Java', 'Runtime', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (76, 'CVE-2026-23525', 'Linux', 'Kernel', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (79, 'CVE-2026-23733', 'Lobehub', 'Lobe Chat', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (84, 'CVE-2026-23829', 'Axllent', 'Mailpit', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (106, 'CVE-2026-0943', 'Harfbuzz', 'Shaper', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (107, 'CVE-2026-1134', 'Php', 'Core', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (108, 'CVE-2026-1135', 'Php', 'Core', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (129, 'CVE-2026-1141', 'Php', 'Core', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (130, 'CVE-2026-1142', 'Asim Qazi', 'Csrf Add Subadmin In News Portal Project In Php An', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (134, 'CVE-2026-1143', 'Lavender', 'Bicycle', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (138, 'CVE-2026-1144', 'Quickjs Ng', 'Quickjs', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (143, 'CVE-2025-29847', 'Apache', 'Http', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (144, 'CVE-2025-59355', 'Apache', 'Http', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (145, 'CVE-2026-1145', 'Paralin', 'Quickjs', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (146, 'CVE-2026-1145', 'Quickjs Ng', 'Quickjs', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (150, 'CVE-2026-1146', 'Php', 'Core', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (151, 'CVE-2026-1147', 'Php', 'Core', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (155, 'CVE-2026-1149', 'Lavender', 'Bicycle', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (159, 'CVE-2026-23745', 'Node.Js', 'Runtime', 0.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (160, 'CVE-2026-23742', 'Kubernetes', 'Container', 0.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (161, 'CVE-2026-23730', 'Php', 'Core', 0.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (162, 'CVE-2026-23729', 'Php', 'Core', 0.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (163, 'CVE-2026-23728', 'Php', 'Core', 0.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (164, 'CVE-2026-23727', 'Php', 'Core', 0.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (165, 'CVE-2026-23726', 'Php', 'Core', 0.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (166, 'CVE-2026-23725', 'Php', 'Core', 0.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (167, 'CVE-2026-23724', 'Php', 'Core', 0.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (168, 'CVE-2026-23723', 'LabRedesCefetRJ', 'WeGIA', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (169, 'CVE-2026-23731', 'LabRedesCefetRJ', 'WeGIA', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (170, 'CVE-2026-23735', 'graphql-hive', 'graphql-modules', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (171, 'CVE-2026-23744', 'MCPJam', 'inspector', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (172, 'CVE-2026-23746', 'Entrust Corporation', 'Instant Financial Issuance (IF)', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (173, 'CVE-2026-23766', 'Istio', 'Istio', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (174, 'CVE-2026-23768', 'NAVER', 'lucy-xss-filter', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (175, 'CVE-2026-23769', 'NAVER', 'lucy-xss-filter', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (176, 'CVE-2026-1148', 'SourceCodester', 'Patients Waiting Area Queue Management System', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (177, 'CVE-2026-1148', 'Patrick Mvuma', 'Patients Waiting Area Queue Management System', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (178, 'CVE-2026-1140', 'UTT', '进取 520W', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (179, 'CVE-2026-1139', 'UTT', '进取 520W', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (180, 'CVE-2026-1138', 'UTT', '进取 520W', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (181, 'CVE-2026-1137', 'UTT', '进取 520W', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (182, 'CVE-2026-1136', 'lcg0124', 'BootDo', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (183, 'CVE-2026-1133', 'Yonyou', 'KSOA', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (184, 'CVE-2026-1132', 'Yonyou', 'KSOA', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (185, 'CVE-2026-1131', 'Yonyou', 'KSOA', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (186, 'CVE-2026-1130', 'Yonyou', 'KSOA', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (187, 'CVE-2026-1129', 'Yonyou', 'KSOA', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (188, 'CVE-2025-15539', 'n/a', 'Open5GS', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (189, 'CVE-2026-23644', 'esm-dev', 'esm.sh', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (190, 'CVE-2026-23626', 'kimai', 'kimai', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (191, 'CVE-2025-15538', 'Open Asset Import Library', 'Assimp', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (192, 'CVE-2026-1125', 'D-Link', 'DIR-823X', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (193, 'CVE-2026-1124', 'Yonyou', 'KSOA', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (194, 'CVE-2026-1123', 'Yonyou', 'KSOA', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (195, 'CVE-2026-1122', 'Yonyou', 'KSOA', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (196, 'CVE-2026-1121', 'Yonyou', 'KSOA', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (197, 'CVE-2026-1120', 'Yonyou', 'KSOA', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (198, 'CVE-2025-15537', 'n/a', 'Mapnik', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (199, 'CVE-2026-1150', 'Lavender', 'Bicycle', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (200, 'CVE-2026-1151', 'technical-laohu', 'mpay', 1.0);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (201, 'CVE-2026-1152', 'Github', 'Bdkuzma', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (202, 'CVE-2026-1152', 'Vuldb', '?Ctiid.341745', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (203, 'CVE-2026-1152', 'Vuldb', '?Id.341745', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (204, 'CVE-2026-1152', 'Vuldb', '?Submit.735775', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (205, 'CVE-2026-1153', 'Github', 'Bdkuzma', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (206, 'CVE-2026-1153', 'Vuldb', '?Ctiid.341746', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (207, 'CVE-2026-1153', 'Vuldb', '?Id.341746', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (208, 'CVE-2026-1153', 'Vuldb', '?Submit.735789', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (209, 'CVE-2026-1154', 'Php', 'Core', 0.7);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (210, 'CVE-2026-1155', 'Lavender', 'Bicycle', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (211, 'CVE-2026-1155', 'Vuldb', '?Ctiid.341749', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (212, 'CVE-2026-1155', 'Vuldb', '?Id.341749', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (213, 'CVE-2026-1155', 'Vuldb', '?Submit.735718', 0.6);
INSERT INTO affected_products (id, cve_id, vendor, product, confidence) VALUES (214, 'CVE-2026-1181', 'Www.Altium', 'Platform', 0.6);
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (1, 'CVE-2026-1106', 'A security flaw has been discovered in Chamilo LMS up to 2.0.0 Beta 1. This issue affects the function deleteLegal of the file src/CoreBundle/Controller/SocialController.php of the component Legal Consent Handler. Performing a manipulation of the argument userId results in improper authorization. The attack is possible to be carried out remotely. The exploit has been released to the public and may be used for attacks. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 5.3, '4.0', '2026-01-18T01:15:51.023000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.773102Z', '2026-01-19T00:06:55.773102Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (2, 'CVE-2026-1107', 'A weakness has been identified in EyouCMS up to 1.7.1/5.0. Impacted is the function check_userinfo of the file Diyajax.php of the component Member Avatar Handler. Executing a manipulation of the argument viewfile can lead to unrestricted upload. The attack may be performed from remote. The exploit has been made available to the public and could be used for attacks. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 5.3, '4.0', '2026-01-18T01:15:51.247000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.775021Z', '2026-01-19T00:06:55.775021Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (3, 'CVE-2026-1108', 'A security vulnerability has been detected in cijliu librtsp up to 2ec1a81ad65280568a0c7c16420d7c10fde13b04. The affected element is the function rtsp_rely_dumps. The manipulation leads to buffer overflow. An attack has to be approached locally. This product is using a rolling release to provide continious delivery. Therefore, no version details for affected nor updated releases are available. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 4.8, '4.0', '2026-01-18T02:16:25.990000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.776748Z', '2026-01-19T00:06:55.776748Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (4, 'CVE-2026-1109', 'A vulnerability was detected in cijliu librtsp up to 2ec1a81ad65280568a0c7c16420d7c10fde13b04. The impacted element is the function rtsp_parse_request. The manipulation results in buffer overflow. Attacking locally is a requirement. This product takes the approach of rolling releases to provide continious delivery. Therefore, version details for affected and updated releases are not available. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 4.8, '4.0', '2026-01-18T04:15:59.613000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.778183Z', '2026-01-19T00:06:55.778183Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (5, 'CVE-2025-15533', 'A vulnerability was determined in raysan5 raylib up to 909f040. Affected by this vulnerability is the function GenImageFontAtlas of the file src/rtext.c. Executing a manipulation can lead to heap-based buffer overflow. The attack can only be executed locally. The exploit has been publicly disclosed and may be utilized. This patch is called 5a3391fdce046bc5473e52afbd835dd2dc127146. Applying a patch is advised to resolve this issue.', 'MEDIUM', 4.8, '4.0', '2026-01-18T05:16:16.360000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.779591Z', '2026-01-19T00:06:55.779591Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (6, 'CVE-2026-1110', 'A flaw has been found in cijliu librtsp up to 2ec1a81ad65280568a0c7c16420d7c10fde13b04. This affects the function rtsp_parse_method. This manipulation causes buffer overflow. It is possible to launch the attack on the local host. Continious delivery with rolling releases is used by this product. Therefore, no version details of affected nor updated releases are available. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 4.8, '4.0', '2026-01-18T05:16:19.280000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.780667Z', '2026-01-19T00:06:55.780667Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (7, 'CVE-2026-1111', 'A vulnerability has been found in Sanluan PublicCMS up to 5.202506.d. This impacts the function Save of the file com/publiccms/controller/admin/sys/TaskTemplateAdminController.java of the component Task Template Management Handler. Such manipulation of the argument path leads to path traversal. The attack can be launched remotely. The exploit has been disclosed to the public and may be used. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 5.1, '4.0', '2026-01-18T06:16:01.007000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.782252Z', '2026-01-19T00:06:55.782252Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (8, 'CVE-2025-15534', 'A vulnerability was identified in raysan5 raylib up to 909f040. Affected by this issue is the function LoadFontData of the file src/rtext.c. The manipulation leads to integer overflow. The attack can only be performed from a local environment. The exploit is publicly available and might be used. The identifier of the patch is 5a3391fdce046bc5473e52afbd835dd2dc127146. It is suggested to install a patch to address this issue.', 'MEDIUM', 4.8, '4.0', '2026-01-18T07:16:01.963000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.783654Z', '2026-01-19T00:06:55.783654Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (9, 'CVE-2026-1112', 'A vulnerability was found in Sanluan PublicCMS up to 5.202506.d. Affected is the function delete of the file publiccms-trade/src/main/java/com/publiccms/controller/web/trade/TradeAddressController.java of the component Trade Address Deletion Endpoint. Performing a manipulation of the argument ids results in improper authorization. The attack may be initiated remotely. The exploit has been made public and could be used. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 5.3, '4.0', '2026-01-18T07:16:03.343000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.785647Z', '2026-01-19T00:06:55.785647Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (10, 'CVE-2025-15535', 'A security flaw has been discovered in nicbarker clay up to 0.14. This affects the function Clay__MeasureTextCached in the library clay.h. The manipulation results in null pointer dereference. The attack is only possible with local access. The exploit has been released to the public and may be used for attacks. The project was informed of the problem early through an issue report but has not responded yet.', 'MEDIUM', 4.8, '4.0', '2026-01-18T08:15:49.057000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.788312Z', '2026-01-19T00:06:55.788312Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (11, 'CVE-2025-15536', 'A weakness has been identified in BYVoid OpenCC up to 1.1.9. This vulnerability affects the function opencc::MaxMatchSegmentation of the file src/MaxMatchSegmentation.cpp. This manipulation causes heap-based buffer overflow. The attack is restricted to local execution. The exploit has been made available to the public and could be used for attacks. Patch name: 345c9a50ab07018f1b4439776bad78a0d40778ec. To fix this issue, it is recommended to deploy a patch.', 'MEDIUM', 4.8, '4.0', '2026-01-18T09:15:46.960000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.789646Z', '2026-01-19T00:06:55.789646Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (12, 'CVE-2025-15537', 'A security vulnerability has been detected in Mapnik up to 4.2.0. This issue affects the function mapnik::dbf_file::string_value of the file plugins/input/shape/dbfile.cpp. Such manipulation leads to heap-based buffer overflow. The attack must be carried out locally. The exploit has been disclosed publicly and may be used. The project was informed of the problem early through an issue report but has not responded yet.', 'MEDIUM', 4.8, '4.0', '2026-01-18T10:15:52.103000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.790807Z', '2026-01-19T00:06:55.790807Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (13, 'CVE-2026-1118', 'A vulnerability was detected in itsourcecode Society Management System 1.0. Impacted is an unknown function of the file /admin/add_activity.php. Performing a manipulation of the argument Title results in sql injection. It is possible to initiate the attack remotely. The exploit is now public and may be used.', 'MEDIUM', 5.3, '4.0', '2026-01-18T11:15:48.860000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.791825Z', '2026-01-19T00:06:55.791825Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (14, 'CVE-2026-1119', 'A flaw has been found in itsourcecode Society Management System 1.0. The affected element is an unknown function of the file /admin/delete_activity.php. Executing a manipulation of the argument activity_id can lead to sql injection. It is possible to launch the attack remotely. The exploit has been published and may be used.', 'MEDIUM', 6.9, '4.0', '2026-01-18T12:15:48.270000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.792503Z', '2026-01-19T00:06:55.792503Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (15, 'CVE-2026-1120', 'A vulnerability has been found in Yonyou KSOA 9.0. The impacted element is an unknown function of the file /worksheet/del_work.jsp of the component HTTP GET Parameter Handler. The manipulation of the argument ID leads to sql injection. The attack can be initiated remotely. The exploit has been disclosed to the public and may be used. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 6.9, '4.0', '2026-01-18T14:16:16.387000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.793909Z', '2026-01-19T00:06:55.793909Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (16, 'CVE-2026-1121', 'A vulnerability was found in Yonyou KSOA 9.0. This affects an unknown function of the file /worksheet/del_workplan.jsp of the component HTTP GET Parameter Handler. The manipulation of the argument ID results in sql injection. The attack can be launched remotely. The exploit has been made public and could be used. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 6.9, '4.0', '2026-01-18T14:16:16.597000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.795301Z', '2026-01-19T00:06:55.795301Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (17, 'CVE-2026-1122', 'A vulnerability was determined in Yonyou KSOA 9.0. This impacts an unknown function of the file /worksheet/work_info.jsp of the component HTTP GET Parameter Handler. This manipulation of the argument ID causes sql injection. The attack may be initiated remotely. The exploit has been publicly disclosed and may be utilized. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 6.9, '4.0', '2026-01-18T14:16:16.783000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.796639Z', '2026-01-19T00:06:55.796639Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (18, 'CVE-2026-1123', 'A vulnerability was identified in Yonyou KSOA 9.0. Affected is an unknown function of the file /worksheet/work_mod.jsp of the component HTTP GET Parameter Handler. Such manipulation of the argument ID leads to sql injection. The attack may be launched remotely. The exploit is publicly available and might be used. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 6.9, '4.0', '2026-01-18T15:15:51.167000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.797967Z', '2026-01-19T00:06:55.797967Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (19, 'CVE-2026-0863', 'Using string formatting and exception handling, an attacker may bypass n8n''s python-task-executor sandbox restrictions and run arbitrary unrestricted Python code in the underlying operating system.

The vulnerability can be exploited via the Code block by an authenticated user with basic permissions and can lead to a full n8n instance takeover on instances operating under "Internal" execution mode.

If the instance is operating under the  "External" execution mode (ex. n8n''s official Docker image) - arbitrary code execution occurs inside a Sidecar container and not the main node, which significantly reduces the vulnerability impact.', 'HIGH', 8.5, '3.1', '2026-01-18T16:15:50.450000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.799828Z', '2026-01-19T00:06:55.799828Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (20, 'CVE-2026-1124', 'A security flaw has been discovered in Yonyou KSOA 9.0. Affected by this vulnerability is an unknown functionality of the file /worksheet/work_report.jsp of the component HTTP GET Parameter Handler. Performing a manipulation of the argument ID results in sql injection. Remote exploitation of the attack is possible. The exploit has been released to the public and may be used for attacks. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 6.9, '4.0', '2026-01-18T16:15:50.630000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.801479Z', '2026-01-19T00:06:55.801479Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (21, 'CVE-2026-1125', 'A weakness has been identified in D-Link DIR-823X 250416. Affected by this issue is the function sub_412E7C of the file /goform/set_wifidog_settings. Executing a manipulation of the argument wd_enable can lead to command injection. The attack can be executed remotely. The exploit has been made available to the public and could be used for attacks.', 'MEDIUM', 6.9, '4.0', '2026-01-18T16:15:50.810000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.803101Z', '2026-01-19T00:06:55.803101Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (22, 'CVE-2026-1126', 'A security vulnerability has been detected in lwj flow up to a3d2fe8133db9d3b50fda4f66f68634640344641. This affects the function uploadFile of the file \flow-master\flow-front-rest\src\main\java\com\dragon\flow\web\resource\flow\FormResource.java of the component SVG File Handler. The manipulation of the argument File leads to unrestricted upload. The attack is possible to be carried out remotely. The exploit has been disclosed publicly and may be used. This product adopts a rolling release strategy to maintain continuous delivery. Therefore, version details for affected or updated releases cannot be specified. The project was informed of the problem early through an issue report but has not responded yet.', 'MEDIUM', 5.3, '4.0', '2026-01-18T17:15:49.713000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.805281Z', '2026-01-19T00:06:55.805281Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (23, 'CVE-2025-15538', 'A security vulnerability has been detected in Open Asset Import Library Assimp up to 6.0.2. Affected by this vulnerability is the function Assimp::LWOImporter::FindUVChannels of the file /src/assimp/code/AssetLib/LWO/LWOMaterial.cpp. Such manipulation leads to use after free. The attack needs to be performed locally. The exploit has been disclosed publicly and may be used. This and similar defects are tracked and handled via issue #6128.', 'MEDIUM', 4.8, '4.0', '2026-01-18T23:15:47.653000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.806583Z', '2026-01-19T00:06:55.806583Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (24, 'CVE-2026-23525', '1Panel is an open-source, web-based control panel for Linux server management. A stored Cross-Site Scripting (XSS) vulnerability exists in the 1Panel App Store when viewing application details. Malicious scripts can execute in the context of the user’s browser, potentially compromising session data or sensitive system interfaces. All versions of 1Panel up to and including v1.10.33-lts and v2.0.16 are affected. An attacker could publish a malicious application that, when loaded by users (locally or remotely), can execute arbitrary scripts. This may result in theft of user cookies, unauthorized access to system functions, or other actions that compromise the confidentiality, integrity, and availability of the system. The vulnerability is caused by insufficient sanitization of content rendered by the MdEditor component with the `previewOnly` attribute enabled. Specifically, the App Store renders application README content without proper XSS protection, allowing script execution during content rendering; and similar issues exist in system upgrade-related components, which can be fixed by implementing proper XSS sanitization in the MdEditor component. These vulnerabilities can be mitigated by applying proper XSS protection and sanitization when rendering content in the MdEditor component. Safe versions with a patch incorporated are v1.10.34-lts and v2.0.17.', 'MEDIUM', 6.4, '3.1', '2026-01-18T23:15:48.220000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.809557Z', '2026-01-19T00:06:55.809557Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (25, 'CVE-2026-23626', 'Kimai is a web-based multi-user time-tracking application. Prior to version 2.46.0, Kimai''s export functionality uses a Twig sandbox with an overly permissive security policy (`DefaultPolicy`) that allows arbitrary method calls on objects available in the template context. An authenticated user with export permissions can deploy a malicious Twig template that extracts sensitive information including environment variables, all user password hashes, serialized session tokens, and CSRF tokens. Version 2.46.0 patches this issue.', 'MEDIUM', 6.8, '3.1', '2026-01-18T23:15:48.393000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.810653Z', '2026-01-19T00:06:55.810653Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (26, 'CVE-2026-23644', 'esm.sh is a no-build content delivery network (CDN) for web development. Prior to Go pseeudoversion 0.0.0-20260116051925-c62ab83c589e, the software has a path traversal vulnerability due to an incomplete fix. `path.Clean` normalizes a path but does not prevent absolute paths in a malicious tar file. Commit https://github.com/esm-dev/esm.sh/commit/9d77b88c320733ff6689d938d85d246a3af9af16, corresponding to pseudoversion 0.0.0-20260116051925-c62ab83c589e, fixes this issue.', 'HIGH', 7.7, '4.0', '2026-01-18T23:15:48.547000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.811474Z', '2026-01-19T00:06:55.811474Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (27, 'CVE-2026-23733', 'LobeChat is an open source chat application platform. Prior to version 2.0.0-next.180, a stored Cross-Site Scripting (XSS) vulnerability in the Mermaid artifact renderer allows attackers to execute arbitrary JavaScript within the application context. This XSS can be escalated to Remote Code Execution (RCE) by leveraging the exposed `electronAPI` IPC bridge, allowing attackers to run arbitrary system commands on the victim''s machine. Version 2.0.0-next.180 patches the issue.', 'MEDIUM', 0.0, '3.1', '2026-01-18T23:15:48.710000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:06:55.812368Z', '2026-01-19T00:06:55.812368Z', 'NVD,cvedetails');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (28, 'CVE-2025-15539', 'A vulnerability was determined in Open5GS up to 2.7.6. Impacted is the function sgwc_s11_handle_downlink_data_notification_ack of the file src/sgwc/s11-handler.c of the component sgwc. This manipulation causes denial of service. The attack can be initiated remotely. The exploit has been publicly disclosed and may be utilized. Patch name: b4707272c1caf6a7d4dca905694ea55557a0545f. To fix this issue, it is recommended to deploy a patch. The issue report is flagged as already-fixed.', 'MEDIUM', 5.5, '4.0', '2026-01-19T00:15:47.693000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:34:49.379524Z', '2026-01-19T00:34:49.379524Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (29, 'CVE-2026-23829', 'Mailpit is an email testing tool and API for developers. Prior to version 1.28. Mailpit''s SMTP server is vulnerable to Header Injection due to an insufficient Regular Expression used to validate `RCPT TO` and `MAIL FROM` addresses. An attacker can inject arbitrary SMTP headers (or corrupt existing ones) by including carriage return characters (`\r`) in the email address. This header injection occurs because the regex intended to filter control characters fails to exclude `\r` and `\n` when used inside a character class. Version 1.28.3 fixes this issue.', 'MEDIUM', 0.0, '3.1', '2026-01-19T00:15:48.707000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T00:34:49.382959Z', '2026-01-19T00:34:49.382959Z', 'NVD,cvedetails');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (30, 'CVE-2026-1129', 'A vulnerability was detected in Yonyou KSOA 9.0. This vulnerability affects unknown code of the file /worksheet/worksadd.jsp of the component HTTP GET Parameter Handler. The manipulation of the argument ID results in sql injection. The attack may be performed from remote. The exploit is now public and may be used. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 6.9, '4.0', '2026-01-19T01:16:00.833000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.029709Z', '2026-01-19T08:15:16.029709Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (31, 'CVE-2026-1130', 'A flaw has been found in Yonyou KSOA 9.0. This issue affects some unknown processing of the file /worksheet/worksadd_plan.jsp of the component HTTP GET Parameter Handler. This manipulation of the argument ID causes sql injection. It is possible to initiate the attack remotely. The exploit has been published and may be used. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 6.9, '4.0', '2026-01-19T01:16:01.033000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.034619Z', '2026-01-19T08:15:16.034619Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (32, 'CVE-2026-1131', 'A vulnerability has been found in Yonyou KSOA 9.0. Impacted is an unknown function of the file /kmc/save_catalog.jsp of the component HTTP GET Parameter Handler. Such manipulation of the argument catalogid leads to sql injection. It is possible to launch the attack remotely. The exploit has been disclosed to the public and may be used. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 6.9, '4.0', '2026-01-19T02:15:56.827000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.036300Z', '2026-01-19T08:15:16.036300Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (33, 'CVE-2026-1132', 'A vulnerability was found in Yonyou KSOA 9.0. The affected element is an unknown function of the file /kmf/edit_folder.jsp of the component HTTP GET Parameter Handler. Performing a manipulation of the argument folderid results in sql injection. The attack can be initiated remotely. The exploit has been made public and could be used. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 6.9, '4.0', '2026-01-19T02:15:57.020000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.037996Z', '2026-01-19T08:15:16.037996Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (34, 'CVE-2026-1133', 'A vulnerability was determined in Yonyou KSOA 9.0. The impacted element is an unknown function of the file /kmf/folder.jsp of the component HTTP GET Parameter Handler. Executing a manipulation of the argument folderid can lead to sql injection. The attack can be launched remotely. The exploit has been publicly disclosed and may be utilized. The vendor was contacted early about this disclosure but did not respond in any way.', 'MEDIUM', 6.9, '4.0', '2026-01-19T03:16:02.023000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.039966Z', '2026-01-19T08:15:16.039966Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (35, 'CVE-2026-0943', 'HarfBuzz::Shaper versions before 0.032 for Perl contains a bundled library with a null pointer dereference vulnerability. 

Versions before 0.032 contain HarfBuzz 8.4.0 or earlier bundled as hb_src.tar.gz in the source tarball, which is affected by CVE-2026-22693.', 'MEDIUM', 5.0, 'N/A', '2026-01-19T04:15:58.710000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.041234Z', '2026-01-19T08:15:16.041234Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (36, 'CVE-2026-1134', 'A vulnerability was identified in itsourcecode Society Management System 1.0. This affects an unknown function of the file /admin/expenses.php. The manipulation of the argument detail leads to cross site scripting. The attack may be initiated remotely. The exploit is publicly available and might be used.', 'MEDIUM', 5.3, '4.0', '2026-01-19T04:15:58.830000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.042302Z', '2026-01-19T08:15:16.042302Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (37, 'CVE-2026-1135', 'A security flaw has been discovered in itsourcecode Society Management System 1.0. This impacts an unknown function of the file /admin/activity.php. The manipulation of the argument Title results in cross site scripting. The attack may be launched remotely. The exploit has been released to the public and may be used for attacks.', 'MEDIUM', 5.3, '4.0', '2026-01-19T04:15:59.123000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.043353Z', '2026-01-19T08:15:16.043353Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (38, 'CVE-2026-1136', 'A weakness has been identified in lcg0124 BootDo up to e93dd428ef6f5c881aa74d49a2099ab0cf1e0fcb. Affected is the function Save of the file /blog/bContent/save of the component ContentController. This manipulation of the argument content/author/title causes cross site scripting. Remote exploitation of the attack is possible. The exploit has been made available to the public and could be used for attacks. This product follows a rolling release approach for continuous delivery, so version details for affected or updated releases are not provided.', 'MEDIUM', 5.1, '4.0', '2026-01-19T04:15:59.303000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.045077Z', '2026-01-19T08:15:16.045077Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (39, 'CVE-2026-1137', 'A vulnerability was detected in UTT 进取 520W 1.7.7-180627. Affected by this issue is the function strcpy of the file /goform/formWebAuthGlobalConfig. Performing a manipulation results in buffer overflow. The attack is possible to be carried out remotely. The exploit is now public and may be used. The vendor was contacted early about this disclosure but did not respond in any way.', 'HIGH', 7.4, '4.0', '2026-01-19T05:16:05.920000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.047595Z', '2026-01-19T08:15:16.047595Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (40, 'CVE-2026-1138', 'A flaw has been found in UTT 进取 520W 1.7.7-180627. This affects the function strcpy of the file /goform/ConfigExceptQQ. Executing a manipulation can lead to buffer overflow. The attack may be performed from remote. The exploit has been published and may be used. The vendor was contacted early about this disclosure but did not respond in any way.', 'HIGH', 7.4, '4.0', '2026-01-19T05:16:09.100000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.049108Z', '2026-01-19T08:15:16.049108Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (41, 'CVE-2026-1139', 'A vulnerability has been found in UTT 进取 520W 1.7.7-180627. This vulnerability affects the function strcpy of the file /goform/ConfigExceptMSN. The manipulation leads to buffer overflow. It is possible to initiate the attack remotely. The exploit has been disclosed to the public and may be used. The vendor was contacted early about this disclosure but did not respond in any way.', 'HIGH', 7.4, '4.0', '2026-01-19T05:16:09.303000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.050691Z', '2026-01-19T08:15:16.050691Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (42, 'CVE-2026-1140', 'A vulnerability was found in UTT 进取 520W 1.7.7-180627. This issue affects the function strcpy of the file /goform/ConfigExceptAli. The manipulation results in buffer overflow. It is possible to launch the attack remotely. The exploit has been made public and could be used. The vendor was contacted early about this disclosure but did not respond in any way.', 'HIGH', 7.4, '4.0', '2026-01-19T06:16:01.640000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.051905Z', '2026-01-19T08:15:16.051905Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (43, 'CVE-2026-1141', 'A vulnerability was identified in PHPGurukul News Portal 1.0. The affected element is an unknown function of the file /admin/add-subadmins.php of the component Add Sub-Admin Page. Such manipulation leads to improper authorization. The attack can be launched remotely. The exploit is publicly available and might be used.', 'MEDIUM', 5.3, '4.0', '2026-01-19T07:16:22.027000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.052992Z', '2026-01-19T08:15:16.052992Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (44, 'CVE-2026-1142', 'A security flaw has been discovered in PHPGurukul News Portal 1.0. The impacted element is an unknown function. Performing a manipulation results in cross-site request forgery. The attack may be initiated remotely. The exploit has been released to the public and may be used for attacks.', 'MEDIUM', 5.3, '4.0', '2026-01-19T07:16:22.457000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.054330Z', '2026-01-19T08:15:16.054330Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (45, 'CVE-2026-1143', 'A weakness has been identified in TOTOLINK A3700R 9.1.2u.5822_B20200513. This affects the function setWiFiEasyGuestCfg of the file /cgi-bin/cstecgi.cgi. Executing a manipulation of the argument ssid can lead to buffer overflow. The attack may be launched remotely. The exploit has been made available to the public and could be used for attacks.', 'HIGH', 7.4, '4.0', '2026-01-19T07:16:22.667000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:15:16.055317Z', '2026-01-19T08:15:16.055317Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (46, 'CVE-2026-1144', 'A vulnerability was detected in quickjs-ng quickjs up to 0.11.0. Affected is an unknown function of the file quickjs.c of the component Atomics Ops Handler. The manipulation results in use after free. The attack can be executed remotely. The exploit is now public and may be used. The patch is identified as ea3e9d77454e8fc9cb3ef3c504e9c16af5a80141. Applying a patch is advised to resolve this issue.', 'MEDIUM', 5.3, '4.0', '2026-01-19T08:16:04.857000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T08:18:09.735030Z', '2026-01-19T08:18:09.735030Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (47, 'CVE-2025-29847', 'A vulnerability in Apache Linkis.

Problem Description
When using the JDBC engine and da
When using the JDBC engine and data source functionality, if the URL parameter configured on the frontend has undergone multiple rounds of URL encoding, it may bypass the system''s checks. This bypass can trigger a vulnerability that allows unauthorized access to system files via JDBC parameters.

Scope of Impact


This issue affects Apache Linkis: from 1.3.0 through 1.7.0.

Severity level


moderate
Solution
Continuously check if the connection information contains the "%" character; if it does, perform URL decoding.

Users are recommended to upgrade to version 1.8.0, which fixes the issue.




More questions about this vulnerability can be discussed here:  https://lists.apache.org/list?dev@linkis.apache.org:2025-9:cve', 'MEDIUM', 5.0, 'N/A', '2026-01-19T09:16:01.237000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T09:27:19.981708Z', '2026-01-19T09:27:19.981708Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (48, 'CVE-2025-59355', 'A vulnerability.

When org.apache.linkis.metadata.util.HiveUtils.decode() fails to perform Base64 decoding, it records the complete input parameter string in the log via logger.error(str + "decode failed", e). If the input parameter contains sensitive information such as Hive Metastore keys, plaintext passwords will be left in the log files when decoding fails, resulting in information leakage.


Affected Scope
Component: Sensitive fields in hive-site.xml (e.g., javax.jdo.option.ConnectionPassword) or other fields encoded in Base64.
Version: Apache Linkis 1.0.0 – 1.7.0


Trigger Conditions
The value of the configuration item is an invalid Base64 string.
Log files are readable by users other than hive-site.xml administrators.


Severity: Low
The probability of Base64 decoding failure is low.
The leakage is only triggered when logs at the Error level are exposed.

Remediation
Apache Linkis 1.8.0 and later versions have replaced the log with desensitized content.
logger.error("URL decode failed: {}", e.getMessage());   // 不再输出 str


Users are recommended to upgrade to version 1.8.0, which fixes the issue.', 'MEDIUM', 5.0, 'N/A', '2026-01-19T09:16:02.107000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T09:27:19.988638Z', '2026-01-19T09:27:19.988638Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (49, 'CVE-2026-1145', 'A flaw has been found in quickjs-ng quickjs up to 0.11.0. Affected by this vulnerability is the function js_typed_array_constructor_ta of the file quickjs.c. This manipulation causes heap-based buffer overflow. The attack is possible to be carried out remotely. The exploit has been published and may be used. Patch name: 53aebe66170d545bb6265906fe4324e4477de8b4. It is suggested to install a patch to address this issue.', 'MEDIUM', 5.3, '4.0', '2026-01-19T09:16:02.587000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T09:27:19.992041Z', '2026-01-19T09:27:19.992041Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (50, 'CVE-2026-1146', 'A vulnerability has been found in SourceCodester/Patrick Mvuma Patients Waiting Area Queue Management System 1.0. Affected by this issue is some unknown functionality of the file /php/api_register_patient.php. Such manipulation of the argument firstName/lastName leads to cross site scripting. The attack may be performed from remote. The exploit has been disclosed to the public and may be used.', 'MEDIUM', 5.1, '4.0', '2026-01-19T09:16:02.803000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T09:27:19.994039Z', '2026-01-19T09:27:19.994039Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (51, 'CVE-2026-1147', 'A vulnerability was found in SourceCodester/Patrick Mvuma Patients Waiting Area Queue Management System 1.0. This affects an unknown part of the file /php/api_patient_schedule.php. Performing a manipulation of the argument Reason results in cross site scripting. It is possible to initiate the attack remotely. The exploit has been made public and could be used.', 'MEDIUM', 5.1, '4.0', '2026-01-19T10:16:08.477000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:16:19.529887Z', '2026-01-19T10:16:19.529887Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (52, 'CVE-2026-1148', 'A vulnerability was determined in SourceCodester/Patrick Mvuma Patients Waiting Area Queue Management System 1.0. This vulnerability affects unknown code. Executing a manipulation can lead to cross-site request forgery. It is possible to launch the attack remotely.', 'MEDIUM', 5.3, '4.0', '2026-01-19T10:16:08.697000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:16:19.561374Z', '2026-01-19T10:16:19.561374Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (53, 'CVE-2026-1149', 'A vulnerability was identified in Totolink LR350 9.3.5u.6369_B20220309. This issue affects the function setDiagnosisCfg of the file /cgi-bin/cstecgi.cgi of the component POST Request Handler. The manipulation of the argument ip leads to command injection. The attack can be initiated remotely. The exploit is publicly available and might be used.', 'MEDIUM', 5.3, '4.0', '2026-01-19T10:16:08.877000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:16:19.595335Z', '2026-01-19T10:16:19.595335Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (54, 'CVE-2026-23800', 'Incorrect Privilege Assignment vulnerability in Modular DS modular-connector allows Privilege Escalation.This issue affects Modular DS: from 2.5.2 before 2.6.0.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 20:40:13', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.811695', '2026-01-19 10:51:15', 'cvedetails,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (55, 'CVE-2026-23769', 'lucy-xss-filter before commit e5826c0 allows an attacker to execute malicious JavaScript due to improper sanitization caused by misconfigured default superset rule files.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 05:23:56', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.814215', '2026-01-19 10:51:15', 'cvedetails,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (56, 'CVE-2026-23768', 'lucy-xss-filter before commit 7c1de6d allows an attacker to induce server-side HEAD requests to arbitrary URLs when the ObjectSecurityListener or EmbedSecurityListener option is enabled and embed or object tags are used with a src attribute missing a file extension.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 05:20:59', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.818082', '2026-01-19 10:51:15', 'cvedetails,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (57, 'CVE-2026-23766', 'Istio through 1.28.2 allows iptables rule injection for changing firewall behavior via the traffic.sidecar.istio.io/excludeInterfaces annotation. NOTE: the reporter''s position is "this doesn''t represent a security vulnerability (pod creators can already exclude sidecar injection entirely)."', 'MEDIUM', 0.0, 'N/A', '2026-01-15 19:18:51', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.820190', '2026-01-19 10:51:15', 'cvedetails,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (58, 'CVE-2026-23746', 'Entrust Instant Financial Issuance (IFI) On Premise software (formerly referred to as CardWizard) versions 5.x, prior to 6.10.5, and prior to 6.11.1 contain an insecure .NET Remoting exposure in the SmartCardController service (DCG.SmartCardControllerService.exe). The service registers a TCP remoting channel with unsafe formatter/settings that permit untrusted remoting object invocation. A remote, unauthenticated attacker who can reach the remoting port can invoke exposed remoting objects to read arbitrary files from the server and coerce outbound authentication, and may achieve arbitrary file write and remote code execution via known .NET Remoting exploitation techniques. This can lead to disclosure of sensitive installation and service-account data and compromise of the affected host.', 'MEDIUM', 0.0, 'N/A', '2026-01-15 20:16:06', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.826499', '2026-01-19 10:51:15', 'cvedetails,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (59, 'CVE-2026-23745', 'node-tar is a Tar for Node.js. The node-tar library (<= 7.5.2) fails to sanitize the linkpath of Link (hardlink) and SymbolicLink entries when preservePaths is false (the default secure behavior). This allows malicious archives to bypass the extraction root restriction, leading to Arbitrary File Overwrite via hardlinks and Symlink Poisoning via absolute symlink targets. This vulnerability is fixed in 7.5.3.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 22:00:09', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.833610', '2026-01-19 10:51:15', 'cvedetails');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (60, 'CVE-2026-23744', 'MCPJam inspector is the local-first development platform for MCP servers. Versions 1.4.2 and earlier are vulnerable to remote code execution (RCE) vulnerability, which allows an attacker to send a crafted HTTP request that triggers the installation of an MCP server, leading to RCE. Since MCPJam inspector by default listens on 0.0.0.0 instead of 127.0.0.1, an attacker can trigger the RCE remotely via a simple HTTP request. Version 1.4.3 contains a patch.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 20:15:52', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.836708', '2026-01-19 10:51:15', 'cvedetails,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (61, 'CVE-2026-23742', 'Skipper is an HTTP router and reverse proxy for service composition. The default skipper configuration before 0.23.0 was -lua-sources=inline,file. The problem starts if untrusted users can create lua filters, because of -lua-sources=inline , for example through a Kubernetes Ingress resource. The configuration inline allows these user to create a script that is able to read the filesystem accessible to the skipper process and if the user has access to read the logs, they an read skipper secrets. This vulnerability is fixed in 0.23.0.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 20:15:52', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.845454', '2026-01-19 10:51:15', 'cvedetails');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (62, 'CVE-2026-23735', 'GraphQL Modules is a toolset of libraries and guidelines dedicated to create reusable, maintainable, testable and extendable modules out of your GraphQL server. From 2.2.1 to before 2.4.1 and 3.1.1, when 2 or more parallel requests are made which trigger the same service, the context of the requests is mixed up in the service when the context is injected via @ExecutionContext(). ExecutionContext is often used to pass authentication tokens from incoming requests to services loading data from backend APIs. This vulnerability is fixed in 2.4.1 and 3.1.1.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 20:15:51', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.849409', '2026-01-19 10:51:15', 'cvedetails,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (63, 'CVE-2026-23731', 'WeGIA is a web manager for charitable institutions. Prior to 3.6.2, The web application is vulnerable to clickjacking attacks. The WeGIA application does not send any defensive HTTP headers related to framing protection. In particular, X-Frame-Options is missing andContent-Security-Policy with frame-ancestors directive is not configured. Because of this, an attacker can load any WeGIA page inside a malicious HTML document, overlay deceptive elements, hide real buttons, or force accidental interaction with sensitive workflows. This vulnerability is fixed in 3.6.2.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 19:50:16', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.857561', '2026-01-19 10:51:15', 'cvedetails,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (64, 'CVE-2026-23730', 'WeGIA is a web manager for charitable institutions. Prior to 3.6.2, an Open Redirect vulnerability was identified in the /WeGIA/controle/control.php endpoint of the WeGIA application, specifically through the nextPage parameter when combined with metodo=listarTodos and nomeClasse=ProdutoControle. The application fails to validate or restrict the nextPage parameter, allowing attackers to redirect users to arbitrary external websites. This can be abused for phishing attacks, credential theft, malware distribution, and social engineering using the trusted WeGIA domain. This vulnerability is fixed in 3.6.2.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 19:48:24', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.864536', '2026-01-19 10:51:15', 'cvedetails');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (65, 'CVE-2026-23729', 'WeGIA is a web manager for charitable institutions. Prior to 3.6.2, an Open Redirect vulnerability was identified in the /WeGIA/controle/control.php endpoint of the WeGIA application, specifically through the nextPage parameter when combined with metodo=listarDescricao and nomeClasse=ProdutoControle. The application fails to validate or restrict the nextPage parameter, allowing attackers to redirect users to arbitrary external websites. This can be abused for phishing attacks, credential theft, malware distribution, and social engineering using the trusted WeGIA domain. This vulnerability is fixed in 3.6.2.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 19:47:10', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.871196', '2026-01-19 10:51:15', 'cvedetails');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (66, 'CVE-2026-23728', 'WeGIA is a web manager for charitable institutions. Prior to 3.6.2, an Open Redirect vulnerability was identified in the /WeGIA/controle/control.php endpoint of the WeGIA application, specifically through the nextPage parameter when combined with metodo=listarTodos and nomeClasse=DestinoControle. The application fails to validate or restrict the nextPage parameter, allowing attackers to redirect users to arbitrary external websites. This can be abused for phishing attacks, credential theft, malware distribution, and social engineering using the trusted WeGIA domain. This vulnerability is fixed in 3.6.2.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 19:46:07', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.878727', '2026-01-19 10:51:15', 'cvedetails');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (67, 'CVE-2026-23727', 'WeGIA is a web manager for charitable institutions. Prior to 3.6.2, an Open Redirect vulnerability was identified in the /WeGIA/controle/control.php endpoint of the WeGIA application, specifically through the nextPage parameter when combined with metodo=listarTodos and nomeClasse=TipoSaidaControle. The application fails to validate or restrict the nextPage parameter, allowing attackers to redirect users to arbitrary external websites. This can be abused for phishing attacks, credential theft, malware distribution, and social engineering using the trusted WeGIA domain. This vulnerability is fixed in 3.6.2.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 19:41:47', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.884948', '2026-01-19 10:51:15', 'cvedetails');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (68, 'CVE-2026-23726', 'WeGIA is a web manager for charitable institutions. Prior to 3.6.2, An Open Redirect vulnerability was identified in the /WeGIA/controle/control.php endpoint of the WeGIA application, specifically through the nextPage parameter when combined with metodo=listarTodos and nomeClasse=TipoEntradaControle. The application fails to validate or restrict the nextPage parameter, allowing attackers to redirect users to arbitrary external websites. This can be abused for phishing attacks, credential theft, malware distribution, and social engineering using the trusted WeGIA domain. This vulnerability is fixed in 3.6.2.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 19:40:05', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.891303', '2026-01-19 10:51:15', 'cvedetails');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (69, 'CVE-2026-23725', 'WeGIA is a web manager for charitable institutions. Prior to 3.6.2, a Stored Cross-Site Scripting (XSS) vulnerability was identified in the html/pet/adotantes/cadastro_adotante.php and html/pet/adotantes/informacao_adotantes.php endpoint of the WeGIA application. The application does not sanitize user-controlled input before rendering it inside the Adopters Information table, allowing persistent JavaScript injection. Any user who visits the page will have the payload executed automatically. This vulnerability is fixed in 3.6.2.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 19:38:27', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.898060', '2026-01-19 10:51:15', 'cvedetails');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (70, 'CVE-2026-23724', 'WeGIA is a web manager for charitable institutions. Prior to 3.6.2, a Stored Cross-Site Scripting (XSS) vulnerability was identified in the html/atendido/cadastro_ocorrencia.php endpoint of the WeGIA application. The application does not sanitize user-controlled data before rendering it inside the “Atendido” selection dropdown. This vulnerability is fixed in 3.6.2.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 19:37:06', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.903400', '2026-01-19 10:51:15', 'cvedetails');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (71, 'CVE-2026-23723', 'WeGIA is a web manager for charitable institutions. Prior to 3.6.2, an authenticated SQL Injection vulnerability was identified in the Atendido_ocorrenciaControle endpoint via the id_memorando parameter. This flaw allows for full database exfiltration, exposure of sensitive PII, and potential arbitrary file reads in misconfigured environments. This vulnerability is fixed in 3.6.2.', 'MEDIUM', 0.0, 'N/A', '2026-01-16 19:27:27', 'PENDING', NULL, NULL, NULL, '2026-01-19T10:51:15.905419', '2026-01-19 10:51:15', 'cvedetails,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (72, 'CVE-2026-1150', 'A security flaw has been discovered in Totolink LR350 9.3.5u.6369_B20220309. Impacted is the function setTracerouteCfg of the file /cgi-bin/cstecgi.cgi of the component POST Request Handler. The manipulation of the argument command results in command injection. The attack can be launched remotely. The exploit has been released to the public and may be used for attacks.', 'MEDIUM', 5.3, '4.0', '2026-01-19T11:15:49.250000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T11:18:41.920776Z', '2026-01-19T11:18:41.920776Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (73, 'CVE-2026-1151', 'A weakness has been identified in technical-laohu mpay up to 1.2.4. The affected element is an unknown function of the component User Center. This manipulation of the argument Nickname causes cross site scripting. The attack may be initiated remotely. The exploit has been made available to the public and could be used for attacks.', 'MEDIUM', 4.8, '4.0', '2026-01-19T11:15:50.047000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T11:18:41.930243Z', '2026-01-19T11:18:41.930243Z', 'NVD,cveorg');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (74, 'CVE-2026-1152', 'A security vulnerability has been detected in technical-laohu mpay up to 1.2.4. The impacted element is an unknown function of the component QR Code Image Handler. Such manipulation of the argument codeimg leads to unrestricted upload. The attack may be launched remotely. The exploit has been disclosed publicly and may be used.', 'MEDIUM', 5.1, '4.0', '2026-01-19T12:15:51.980000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T12:39:00.483702Z', '2026-01-19T12:39:00.483702Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (75, 'CVE-2026-1153', 'A vulnerability was detected in technical-laohu mpay up to 1.2.4. This affects an unknown function. Performing a manipulation results in cross-site request forgery. Remote exploitation of the attack is possible. The exploit is now public and may be used.', 'MEDIUM', 5.3, '4.0', '2026-01-19T13:16:20.007000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T13:39:04.244836Z', '2026-01-19T13:39:04.244836Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (76, 'CVE-2026-1154', 'A flaw has been found in SourceCodester E-Learning System 1.0. This impacts an unknown function of the file /admin/modules/lesson/index.php of the component Lesson Module Handler. Executing a manipulation of the argument Title/Description can lead to basic cross site scripting. The attack can be executed remotely. The exploit has been published and may be used.', 'MEDIUM', 5.3, '4.0', '2026-01-19T13:16:20.177000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T13:39:04.264905Z', '2026-01-19T13:39:04.264905Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (77, 'CVE-2026-1155', 'A vulnerability was found in Totolink LR350 9.3.5u.6369_B20220309. Affected by this vulnerability is the function setWiFiEasyGuestCfg of the file /cgi-bin/cstecgi.cgi. The manipulation of the argument ssid results in buffer overflow. The attack may be performed from remote. The exploit has been made public and could be used.', 'HIGH', 7.4, '4.0', '2026-01-19T13:16:20.360000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T13:39:04.276810Z', '2026-01-19T13:39:04.276810Z', 'NVD');
INSERT INTO cves (id, cve_id, description, severity, cvss_score, cvss_version, published_date, status, analyst, decision_date, decision_comments, imported_at, last_updated, source) VALUES (78, 'CVE-2026-1181', 'A stored cross-site scripting (XSS) vulnerability exists in the Altium Forum due to missing server-side input sanitization in forum post content. An authenticated attacker can inject arbitrary JavaScript into forum posts, which is stored and executed when other users view the affected post.
Successful exploitation allows the attacker’s payload to execute in the context of the victim’s authenticated Altium 365 session, enabling unauthorized access to workspace data, including design files and workspace settings. Exploitation requires user interaction to view a malicious forum post.', 'CRITICAL', 9.0, '3.1', '2026-01-19T13:16:20.543000Z', 'PENDING', NULL, NULL, NULL, '2026-01-19T13:39:04.283941Z', '2026-01-19T13:39:04.283941Z', 'NVD');
INSERT INTO users (id, username, role, password_hash, password_salt, created_at) VALUES (1, 'analyst1', 'VOC_L1', 'f21ba7f26ef7ff9f8107679641ee92a54f04a700950abfc8963fd7f92772620f', '3aee1dcd2c6ca4f2360352483ca1a306', '2026-01-19 00:06:46');
INSERT INTO users (id, username, role, password_hash, password_salt, created_at) VALUES (2, 'lead1', 'VOC_LEAD', '837d9eaaedd8eba89465d1c1c29ef4654e0e7855cf496dbcdafabcd6604a78db', '669192fb462ef9c87b712f426651fec3', '2026-01-19 00:06:46');
INSERT INTO users (id, username, role, password_hash, password_salt, created_at) VALUES (3, 'admin', 'ADMINISTRATOR', '3f033e1bfa2bfd5035a446c67afc5ab21e501c9fab9b096e2f47b8c48bf878aa', 'd8499eac933e60208286055e21de240a', '2026-01-19 00:06:46');
INSERT INTO users (id, username, role, password_hash, password_salt, created_at) VALUES (4, 'manager1', 'MANAGER', '94ced95c6b39a25eb71777e4858b3b096f6bbd1c74027f4211947cc92dfd2f09', 'df158422cfac9b51870907078d00f460', '2026-01-19 00:06:46');

-- Migration completed
