import React, { useState } from 'react';
import axios from 'axios';

const API_URL = 'http://localhost:8000';

const AIRemediationPanelSimple = ({ cveId, cveSeverity, cveScore }) => {
  const [loading, setLoading] = useState(false);
  const [remediation, setRemediation] = useState(null);
  const [error, setError] = useState(null);
  const [expandedSections, setExpandedSections] = useState({
    immediate: true,
    patches: false,
    workarounds: false,
    verification: false
  });

  const generateRemediation = async () => {
    setLoading(true);
    setError(null);
    
    try {
      const token = localStorage.getItem('ctba_token');
      
      const response = await axios.post(
        `${API_URL}/api/ai/remediation/${cveId}`,
        {},
        {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        }
      );
      
      setRemediation(response.data.remediation);
      
    } catch (err) {
      console.error('Error generating AI remediation:', err);
      setError(
        err.response?.data?.detail || 
        'Error generating AI recommendations'
      );
    } finally {
      setLoading(false);
    }
  };

  const getSeverityColor = (severity) => {
    switch (severity?.toUpperCase()) {
      case 'CRITICAL': return '#dc2626';
      case 'HIGH': return '#ea580c';
      case 'MEDIUM': return '#f59e0b';
      case 'LOW': return '#22c55e';
      default: return '#64748b';
    }
  };

  const toggleSection = (section) => {
    setExpandedSections(prev => ({
      ...prev,
      [section]: !prev[section]
    }));
  };

  const formatText = (text) => {
    if (!text) return null;
    const lines = text.split('\n').filter(line => line.trim());
    return (
      <ul style={{ paddingLeft: '20px', margin: '10px 0' }}>
        {lines.map((line, index) => (
          <li key={index} style={{ marginBottom: '8px' }}>
            {line.replace(/^[-•]\s*/, '')}
          </li>
        ))}
      </ul>
    );
  };

  const accordionStyle = {
    border: '1px solid #e2e8f0',
    borderRadius: '8px',
    marginBottom: '10px',
    overflow: 'hidden',
    backgroundColor: '#fff'
  };

  const accordionHeaderStyle = (color) => ({
    padding: '12px 16px',
    backgroundColor: '#f8fafc',
    cursor: 'pointer',
    display: 'flex',
    alignItems: 'center',
    gap: '10px',
    fontWeight: '600',
    borderBottom: '1px solid #e2e8f0',
    transition: 'background-color 0.2s'
  });

  const accordionContentStyle = {
    padding: '16px',
    fontSize: '14px',
    lineHeight: '1.6'
  };

  return (
    <div style={{
      backgroundColor: '#f8f9fa',
      border: '1px solid #e2e8f0',
      borderRadius: '12px',
      padding: '20px',
      marginTop: '20px'
    }}>
      <div style={{ 
        display: 'flex', 
        alignItems: 'center', 
        justifyContent: 'space-between',
        marginBottom: '15px'
      }}>
        <div style={{ display: 'flex', alignItems: 'center', gap: '10px' }}>
          <span style={{ fontSize: '24px' }}>🤖</span>
          <h3 style={{ margin: 0, fontSize: '18px', color: '#1e293b' }}>
            AI-Assisted Remediation
          </h3>
        </div>
        {cveSeverity && (
          <span style={{
            padding: '4px 12px',
            borderRadius: '6px',
            fontSize: '12px',
            fontWeight: '600',
            backgroundColor: getSeverityColor(cveSeverity),
            color: '#fff'
          }}>
            {cveSeverity} ({cveScore || 'N/A'})
          </span>
        )}
      </div>

      {!remediation && !loading && (
        <div style={{ textAlign: 'center', padding: '20px' }}>
          <p style={{ color: '#64748b', marginBottom: '15px' }}>
            Get automated remediation recommendations generated by AI
          </p>
          <button
            className="btn btn-primary"
            onClick={generateRemediation}
            disabled={loading}
            style={{
              display: 'inline-flex',
              alignItems: 'center',
              gap: '8px',
              padding: '10px 20px',
              fontSize: '14px'
            }}
          >
            <span>🤖</span>
            Generate AI Recommendations
          </button>
        </div>
      )}

      {loading && (
        <div style={{ 
          textAlign: 'center', 
          padding: '30px',
          color: '#64748b'
        }}>
          <div className="spinner-border" role="status" style={{ marginBottom: '10px' }}>
            <span className="sr-only">Loading...</span>
          </div>
          <p>Generating recommendations...</p>
        </div>
      )}

      {error && (
        <div className="alert alert-danger" role="alert">
          {error}
        </div>
      )}

      {remediation && (
        <div>
          <hr style={{ margin: '15px 0', borderColor: '#e2e8f0' }} />
          
          {/* Actions Immédiates */}
          {remediation.immediate_actions && (
            <div style={accordionStyle}>
              <div 
                style={{
                  ...accordionHeaderStyle(),
                  backgroundColor: expandedSections.immediate ? '#fef2f2' : '#f8fafc'
                }}
                onClick={() => toggleSection('immediate')}
              >
                <span style={{ color: '#dc2626', fontSize: '20px' }}>⚠️</span>
                <span>Immediate Actions</span>
                <span style={{ marginLeft: 'auto', fontSize: '12px' }}>
                  {expandedSections.immediate ? '▼' : '▶'}
                </span>
              </div>
              {expandedSections.immediate && (
                <div style={accordionContentStyle}>
                  {formatText(remediation.immediate_actions)}
                </div>
              )}
            </div>
          )}

          {/* Correctifs et Patches */}
          {remediation.patches && (
            <div style={accordionStyle}>
              <div 
                style={{
                  ...accordionHeaderStyle(),
                  backgroundColor: expandedSections.patches ? '#eff6ff' : '#f8fafc'
                }}
                onClick={() => toggleSection('patches')}
              >
                <span style={{ color: '#2563eb', fontSize: '20px' }}>🔧</span>
                <span>Fixes and Patches</span>
                <span style={{ marginLeft: 'auto', fontSize: '12px' }}>
                  {expandedSections.patches ? '▼' : '▶'}
                </span>
              </div>
              {expandedSections.patches && (
                <div style={accordionContentStyle}>
                  {formatText(remediation.patches)}
                </div>
              )}
            </div>
          )}

          {/* Solutions de Contournement */}
          {remediation.workarounds && (
            <div style={accordionStyle}>
              <div 
                style={{
                  ...accordionHeaderStyle(),
                  backgroundColor: expandedSections.workarounds ? '#fffbeb' : '#f8fafc'
                }}
                onClick={() => toggleSection('workarounds')}
              >
                <span style={{ color: '#f59e0b', fontSize: '20px' }}>🛠️</span>
                <span>Workarounds</span>
                <span style={{ marginLeft: 'auto', fontSize: '12px' }}>
                  {expandedSections.workarounds ? '▼' : '▶'}
                </span>
              </div>
              {expandedSections.workarounds && (
                <div style={accordionContentStyle}>
                  {formatText(remediation.workarounds)}
                </div>
              )}
            </div>
          )}

          {/* Vérification */}
          {remediation.verification && (
            <div style={accordionStyle}>
              <div 
                style={{
                  ...accordionHeaderStyle(),
                  backgroundColor: expandedSections.verification ? '#f0fdf4' : '#f8fafc'
                }}
                onClick={() => toggleSection('verification')}
              >
                <span style={{ color: '#16a34a', fontSize: '20px' }}>✅</span>
                <span>Verification</span>
                <span style={{ marginLeft: 'auto', fontSize: '12px' }}>
                  {expandedSections.verification ? '▼' : '▶'}
                </span>
              </div>
              {expandedSections.verification && (
                <div style={accordionContentStyle}>
                  {formatText(remediation.verification)}
                </div>
              )}
            </div>
          )}

          {/* Note */}
          {remediation.note && (
            <div className="alert alert-info" style={{ 
              marginTop: '15px',
              fontSize: '13px'
            }}>
              {remediation.note}
            </div>
          )}

          {/* Bouton Régénérer */}
          <div style={{ textAlign: 'center', marginTop: '15px' }}>
            <button
              className="btn btn-outline-secondary btn-sm"
              onClick={generateRemediation}
              disabled={loading}
              style={{
                display: 'inline-flex',
                alignItems: 'center',
                gap: '6px'
              }}
            >
              <span>🤖</span>
              Regenerate Recommendations
            </button>
          </div>
        </div>
      )}
    </div>
  );
};

export default AIRemediationPanelSimple;
