import React, { useState } from 'react';
import {
  Box,
  Card,
  CardContent,
  Button,
  Typography,
  CircularProgress,
  Alert,
  Accordion,
  AccordionSummary,
  AccordionDetails,
  Chip,
  Divider
} from '@mui/material';
import {
  Psychology,
  ExpandMore,
  Warning,
  Build,
  CheckCircle,
  Info
} from '@mui/icons-material';
import axios from 'axios';

const API_URL = 'http://localhost:8000';

const AIRemediationPanel = ({ cveId, cveSeverity, cveScore }) => {
  const [loading, setLoading] = useState(false);
  const [remediation, setRemediation] = useState(null);
  const [error, setError] = useState(null);

  const generateRemediation = async () => {
    setLoading(true);
    setError(null);
    
    try {
      const token = localStorage.getItem('ctba_token');
      
      const response = await axios.post(
        `${API_URL}/api/ai/remediation/${cveId}`,
        {},
        {
          headers: {
            'Authorization': `Bearer ${token}`
          }
        }
      );
      
      setRemediation(response.data.remediation);
      
    } catch (err) {
      console.error('Error generating AI remediation:', err);
      setError(
        err.response?.data?.detail || 
        'Error generating AI recommendations'
      );
    } finally {
      setLoading(false);
    }
  };

  const getSeverityColor = (severity) => {
    switch (severity?.toUpperCase()) {
      case 'CRITICAL': return 'error';
      case 'HIGH': return 'warning';
      case 'MEDIUM': return 'info';
      case 'LOW': return 'success';
      default: return 'default';
    }
  };

  const formatText = (text) => {
    if (!text) return null;
    
    // Convertir les lignes commençant par - en liste
    const lines = text.split('\n').filter(line => line.trim());
    
    return (
      <Box component="ul" sx={{ pl: 2, mb: 0 }}>
        {lines.map((line, index) => (
          <li key={index} style={{ marginBottom: '8px' }}>
            {line.replace(/^[-•]\s*/, '')}
          </li>
        ))}
      </Box>
    );
  };

  return (
    <Card sx={{ mt: 2, backgroundColor: '#f8f9fa' }}>
      <CardContent>
        <Box sx={{ display: 'flex', alignItems: 'center', mb: 2 }}>
          <Psychology sx={{ mr: 1, color: '#1976d2', fontSize: 28 }} />
          <Typography variant="h6" component="div">
            AI-Assisted Remediation
          </Typography>
          {cveSeverity && (
            <Chip
              label={`${cveSeverity} (${cveScore || 'N/A'})`}
              color={getSeverityColor(cveSeverity)}
              size="small"
              sx={{ ml: 'auto' }}
            />
          )}
        </Box>

        {!remediation && !loading && (
          <Box sx={{ textAlign: 'center', py: 2 }}>
            <Typography variant="body2" color="text.secondary" sx={{ mb: 2 }}>
              Get automated remediation recommendations generated by AI
            </Typography>
            <Button
              variant="contained"
              color="primary"
              startIcon={<Psychology />}
              onClick={generateRemediation}
              disabled={loading}
            >
              Generate AI Recommendations
            </Button>
          </Box>
        )}

        {loading && (
          <Box sx={{ display: 'flex', justifyContent: 'center', py: 3 }}>
            <CircularProgress />
            <Typography sx={{ ml: 2 }}>
              Generating recommendations...
            </Typography>
          </Box>
        )})

        {error && (
          <Alert severity="error" sx={{ mb: 2 }}>
            {error}
          </Alert>
        )}

        {remediation && (
          <Box>
            <Divider sx={{ mb: 2 }} />
            
            {/* Actions Immédiates */}
            {remediation.immediate_actions && (
              <Accordion defaultExpanded>
                <AccordionSummary expandIcon={<ExpandMore />}>
                  <Box sx={{ display: 'flex', alignItems: 'center' }}>
                    <Warning sx={{ mr: 1, color: '#d32f2f' }} />
                    <Typography sx={{ fontWeight: 'bold' }}>
                      Immediate Actions
                    </Typography>
                  </Box>
                </AccordionSummary>
                <AccordionDetails>
                  <Typography component="div" variant="body2">
                    {formatText(remediation.immediate_actions)}
                  </Typography>
                </AccordionDetails>
              </Accordion>
            )}

            {/* Correctifs et Patches */}
            {remediation.patches && (
              <Accordion>
                <AccordionSummary expandIcon={<ExpandMore />}>
                  <Box sx={{ display: 'flex', alignItems: 'center' }}>
                    <Build sx={{ mr: 1, color: '#1976d2' }} />
                    <Typography sx={{ fontWeight: 'bold' }}>
                      Fixes and Patches
                    </Typography>
                  </Box>
                </AccordionSummary>
                <AccordionDetails>
                  <Typography component="div" variant="body2">
                    {formatText(remediation.patches)}
                  </Typography>
                </AccordionDetails>
              </Accordion>
            )}

            {/* Solutions de Contournement */}
            {remediation.workarounds && (
              <Accordion>
                <AccordionSummary expandIcon={<ExpandMore />}>
                  <Box sx={{ display: 'flex', alignItems: 'center' }}>
                    <Info sx={{ mr: 1, color: '#f57c00' }} />
                    <Typography sx={{ fontWeight: 'bold' }}>
                      Workarounds
                    </Typography>
                  </Box>
                </AccordionSummary>
                <AccordionDetails>
                  <Typography component="div" variant="body2">
                    {formatText(remediation.workarounds)}
                  </Typography>
                </AccordionDetails>
              </Accordion>
            )}

            {/* Vérification */}
            {remediation.verification && (
              <Accordion>
                <AccordionSummary expandIcon={<ExpandMore />}>
                  <Box sx={{ display: 'flex', alignItems: 'center' }}>
                    <CheckCircle sx={{ mr: 1, color: '#2e7d32' }} />
                    <Typography sx={{ fontWeight: 'bold' }}>
                      Verification
                    </Typography>
                  </Box>
                </AccordionSummary>
                <AccordionDetails>
                  <Typography component="div" variant="body2">
                    {formatText(remediation.verification)}
                  </Typography>
                </AccordionDetails>
              </Accordion>
            )}

            {/* Note */}
            {remediation.note && (
              <Alert severity="info" sx={{ mt: 2 }}>
                {remediation.note}
              </Alert>
            )}

            {/* Bouton Régénérer */}
            <Box sx={{ mt: 2, textAlign: 'center' }}>
              <Button
                variant="outlined"
                size="small"
                startIcon={<Psychology />}
                onClick={generateRemediation}
                disabled={loading}
              >
                Regenerate Recommendations
              </Button>
            </Box>
          </Box>
        )}
      </CardContent>
    </Card>
  );
};

export default AIRemediationPanel;
